### PR TITLE
Only graph when data is present

### LINKED ISSUE #393: Diagnostic plot point size causes crash with zero data
Steps to reproduce
1. Install WPILIb 2022.4.1 on a new system
2. Open SysID from Start (No data should be loaded)
4. Go to the Diagnostic Plots window and adjust the point size slider.

This particular system is running Win11 21H2, but this also happens on both Win10 20H1 and 21H2. No error message is returned, the GUI just closes.

### PR DESCRIPTION
**Pull request by Piphi5**
Fixes #393 

Previously changing the graphing settings before any data was present would lead to it crashing.

### CODE REVIEW

File: sysid-application/src/main/native/include/sysid/analysis/AnalysisManager.h [hunk 1]
```diff
@@ -309,6 +309,12 @@ class AnalysisManager {
    */
   const std::array<units::second_t, 4> GetStartTimes() { return m_startTimes; }
 
+  const bool HasData() {
+    return !m_originalDataset[static_cast<int>(
+                                  Settings::DrivetrainDataset::kCombined)]
+                .empty();
+  }
```
Comment (calcmogul) [inline sysid-application/src/main/native/include/sysid/analysis/AnalysisManager.h:316]:
```suggestion
  const std::array<units::second_t, 4>& GetStartTimes() const { return m_startTimes; }

  bool HasData() const {
    return !m_originalDataset[static_cast<int>(
                                  Settings::DrivetrainDataset::kCombined)]
                .empty();
  }
```

**Review by calcmogul — CHANGES_REQUESTED** [review]

**Review by calcmogul — APPROVED** [review]
