### PR TITLE
Fix CTRE Feedback Controller Presets

### LINKED ISSUE #272: Update CTRE Feedback Controller Presets
Currently, the CTRE Presets are very unclear:
image

### PR DESCRIPTION
**Pull request by Piphi5**
Fixes #272

### CODE REVIEW

File: sysid-application/src/main/native/include/sysid/analysis/FeedbackControllerPreset.h [hunk 1]
```diff
@@ -103,10 +103,10 @@ constexpr FeedbackControllerPreset kWPILibOld{1.0 / 12.0, 1.0, 50_ms, false,
...
  * Total delay = 50 ms + 31.5 ms = 81.5 ms.
  */
-constexpr FeedbackControllerPreset kCTRENew{1.0 / 12.0, 0.1, 1_ms, true,
-                                            81.5_ms};
-constexpr FeedbackControllerPreset kCTREOld{1023.0 / 12.0, 0.1, 1_ms, false,
-                                            81.5_ms};
+constexpr FeedbackControllerPreset kCTRECANCoder{1.0 / 12.0, 60.0, 1_ms, true,
+                                                 81.5_ms};
+constexpr FeedbackControllerPreset kCTREDefault{1024.0 / 12.0, 0.1, 1_ms, false,
+                                                81.5_ms};
```
Comment (Piphi5) [inline sysid-application/src/main/native/include/sysid/analysis/FeedbackControllerPreset.h:109]: Could someone verify that these are the proper settings for the two different types?

File: sysid-application/src/main/native/include/sysid/analysis/FeedbackControllerPreset.h [hunk 2]
```diff
@@ -103,10 +103,10 @@ constexpr FeedbackControllerPreset kWPILibOld{1.0 / 12.0, 1.0, 50_ms, false,
  *
  * Total delay = 50 ms + 31.5 ms = 81.5 ms.
  */
-constexpr FeedbackControllerPreset kCTRENew{1.0 / 12.0, 0.1, 1_ms, true,
-                                            81.5_ms};
-constexpr FeedbackControllerPreset kCTREOld{1023.0 / 12.0, 0.1, 1_ms, false,
-                                            81.5_ms};
+constexpr FeedbackControllerPreset kCTRECANCoder{1.0 / 12.0, 60.0, 1_ms, true,
+                                                 81.5_ms};
+constexpr FeedbackControllerPreset kCTREDefault{1024.0 / 12.0, 0.1, 1_ms, false,
```
Comment (prateekma) [inline sysid-application/src/main/native/include/sysid/analysis/FeedbackControllerPreset.h:108]: This should be 1023

**Review by prateekma — CHANGES_REQUESTED** [review]

**Review by calcmogul — APPROVED** [review]
