### PR TITLE
Fix Step Voltage default data trim

### LINKED ISSUE #175: Program crashes when loading data file
Attached the data file. This was saved after doing all 4 tests. 

[sysid_data20210822-104822.zip](https://github.com/wpilibsuite/sysid/files/7027725/sysid_data20210822-104822.zip)

I don't see any kind of log or other information that I can include here, is there a way to generate debugging info?

### PR DESCRIPTION
**Pull request by Piphi5**
Fixes #175

### CODE REVIEW

File: sysid-application/src/main/native/cpp/analysis/FilteringUtils.cpp [hunk 1]
```diff
@@ -96,10 +95,14 @@ units::second_t sysid::TrimStepVoltageData(std::vector<PreparedData>* data,
           return std::abs(entry.acceleration) > accelNoiseFloor;
         });
 
-    // Calculate default duration
-    settings->stepTestDuration =
-        std::min(endIt->timestamp - data->front().timestamp + minStepTime + 1_s,
-                 maxStepTime);
+    if (endIt != data->rend()) {
```
Comment (calcmogul) [inline sysid-application/src/main/native/cpp/analysis/FilteringUtils.cpp:98]: Why `rend()` instead of `end()`?

File: sysid-application/src/main/native/cpp/analysis/FilteringUtils.cpp [hunk 2]
```diff
@@ -73,7 +73,6 @@ units::second_t sysid::TrimStepVoltageData(std::vector<PreparedData>* data,
                                            units::second_t minStepTime,
                                            units::second_t maxStepTime) {
   auto firstTimestamp = data->at(0).timestamp;
-
```
Comment (calcmogul) [inline sysid-application/src/main/native/cpp/analysis/FilteringUtils.cpp:76]: This doesn't need to be removed.

File: sysid-application/src/main/native/cpp/analysis/FilteringUtils.cpp [hunk 3]
```diff
@@ -259,7 +262,6 @@ void sysid::InitialTrimAndFilter(
     AnalysisManager::Settings& settings, units::second_t& minStepTime,
     units::second_t& maxStepTime, std::string_view unit) {
   auto& preparedData = *data;
-
```
Comment (calcmogul) [inline sysid-application/src/main/native/cpp/analysis/FilteringUtils.cpp:262]: This doesn't need to be removed.

**Review by calcmogul — CHANGES_REQUESTED** [review]

File: sysid-application/src/main/native/cpp/analysis/FilteringUtils.cpp (hunk 1 above)
Comment (Piphi5) [reply sysid-application/src/main/native/cpp/analysis/FilteringUtils.cpp:98]: I think endIt is a reverse iterator. Does it not make a difference if I use `end()`?

Comment (calcmogul) [reply sysid-application/src/main/native/cpp/analysis/FilteringUtils.cpp:99]: Oh, I see. In that case, we should probably change this:
```cpp
    auto endIt = std::find_if(
        std::reverse_iterator{data->end()},
        std::reverse_iterator{data->begin()}, [&](const PreparedData& entry) {
          return std::abs(entry.acceleration) > accelNoiseFloor;
        });
```
to this:
```cpp
    auto endIt = std::find_if(
        data->rend(), data->rbegin(), [&](const PreparedData& entry) {
          return std::abs(entry.acceleration) > accelNoiseFloor;
        });
```

Comment (PeterJohnson) [reply sysid-application/src/main/native/cpp/analysis/FilteringUtils.cpp:98]: Wouldn’t that be rbegin(), rend()?  The rbegin() function returns the reverse iterator starting at the end of the container.

Comment (Piphi5) [reply sysid-application/src/main/native/cpp/analysis/FilteringUtils.cpp:98]: Yeah, it is that. It doesn't compile otherwise.

**Review by calcmogul — APPROVED** [review]

**Comment by Piphi5** [comment]
We should just double check to make sure the issue is fully resolved on Will's end before merging.
