### PR TITLE
Disable analysis when an exception is thrown

### LINKED ISSUE #74: DARE exception prevents loading JSON and modifying settings to fix it
1. Open the following JSON (extension changed to .txt because GitHub can't do .json):
[characterization-data20210317-1925_new.txt](https://github.com/wpilibsuite/sysid/files/6165503/characterization-data20210317-1925_new.txt)
2. Set the window size to 2 and the velocity threshold to 15 in the feedforward analysis settings

The DARE will throw an exception at discrete_algebraic_riccati_equation.cpp:37 saying that the system isn't stabilizable. This aborts the JSON load, which means the settings can't be fixed to avoid the error. Reopening sysid resets the settings to defaults, so the JSON can be loaded again.

We should report an error for the feedback analysis section, but still allow loading the JSON and tweaking the feedforward analysis settings.

### PR DESCRIPTION
**Pull request by Piphi5**
Whenever an exception is caught, the tool disables data analysis until a feedforward value is changed. This lets users change the data without having to reload the file.

Fixes #74

### CODE REVIEW

**Comment by Piphi5** [comment]
Should this also be done for the Feedback gains?

**Comment by calcmogul** [comment]
Yes.

File: sysid-application/src/main/native/cpp/view/Analyzer.cpp [hunk 1]
```diff
@@ -485,31 +498,35 @@ void Analyzer::SelectFile() {
...
-    m_exception =
-        "The provided JSON was invalid! You may need to rerun the logger.\n" +
-        std::string(e.what());
-    ResetManagerState();
-    ImGui::OpenPopup("Exception Caught!");
-  } catch (const std::exception& e) {
-    m_exception = e.what();
-    ResetManagerState();
-    ImGui::OpenPopup("Exception Caught!");
+  if (m_enabled) {
```
Comment (calcmogul) [inline sysid-application/src/main/native/cpp/view/Analyzer.cpp:501]: You could reduce nesting here by putting this at the top instead:
```cpp
if (!m_enabled) {
  return;
}
```

File: sysid-application/src/main/native/cpp/view/Analyzer.cpp [hunk 2]
```diff
@@ -485,31 +498,35 @@ void Analyzer::SelectFile() {
...
   try {
-    const auto& [ff, fb, trackWidth] = m_manager->Calculate();
-    m_ff = std::get<0>(ff);
-    m_rSquared = std::get<1>(ff);
-    m_Kp = fb.Kp;
-    m_Kd = fb.Kd;
-    m_trackWidth = trackWidth;
-    m_unit = m_manager->GetUnit();
-    m_factor = m_manager->GetFactor();
+    if (m_enabled) {
```
Comment (calcmogul) [inline sysid-application/src/main/native/cpp/view/Analyzer.cpp:520]: Make the function exit before the try block if analysis is disabled.

File: sysid-application/src/main/native/cpp/view/Analyzer.cpp [hunk 3]
```diff
@@ -526,17 +543,19 @@ void Analyzer::AbortDataPrep() {
...
-    m_dataThread = std::thread([&] {
-      m_plot.SetData(m_manager->GetRawData(), m_manager->GetFilteredData(),
-                     m_manager->GetUnit(), m_ff, m_manager->GetStartTimes(),
-                     m_type, m_abortDataPrep);
-    });
-  } catch (const std::exception& e) {
-    m_exception = e.what();
-    ResetManagerState();
-    ImGui::OpenPopup("Exception Caught!");
+  if (m_enabled) {
```
Comment (calcmogul) [inline sysid-application/src/main/native/cpp/view/Analyzer.cpp:546]: Make the function exit before the try block if analysis is disabled.

**Review by calcmogul — CHANGES_REQUESTED** [review]

**Comment by calcmogul** [comment]
I can't even get nonzero P and D gains on main, so idk how to test this PR.

**Comment by calcmogul** [comment]
If I apply this patch:
```diff
diff --git a/sysid-application/src/main/native/cpp/analysis/FeedbackAnalysis.cpp b/sysid-application/src/main/native/cpp/analysis/FeedbackAnalysis.cpp
index 2732976..ad74f9e 100644
--- a/sysid-application/src/main/native/cpp/analysis/FeedbackAnalysis.cpp
+++ b/sysid-application/src/main/native/cpp/analysis/FeedbackAnalysis.cpp
@@ -31,6 +31,7 @@ FeedbackGains sysid::CalculatePositionFeedbackGains(
     // Create an LQR with 2 states to control -- position and velocity.
     frc::LinearQuadraticRegulator<2, 1> controller{
         system, {params.qp, params.qv}, {params.r}, preset.period};
+    throw std::runtime_error("TEST");
     // Compensate for any latency from sensor measurements, filtering, etc.
     controller.LatencyCompensate(system, preset.period,
                                  preset.positionMeasurementDelay);
@@ -48,6 +49,7 @@ FeedbackGains sysid::CalculatePositionFeedbackGains(
   // Create an LQR with one state -- position.
   frc::LinearQuadraticRegulator<1, 1> controller{
       system, {params.qp}, {params.r}, preset.period};
+  throw std::runtime_error("TEST");
   // Compensate for any latency from sensor measurements, filtering, etc.
   controller.LatencyCompensate(system, preset.period,
                                preset.positionMeasurementDelay);
@@ -72,6 +74,7 @@ FeedbackGains sysid::CalculateVelocityFeedbackGains(
   // Create an LQR controller with 1 state -- velocity.
   frc::LinearQuadraticRegulator<1, 1> controller{
       system, {params.qv}, {params.r}, preset.period};
+  throw std::runtime_error("TEST");
   // Compensate for any latency from sensor measurements, filtering, etc.
   controller.LatencyCompensate(system, preset.period,
                                preset.velocityMeasurementDelay);
```
With this data: [noisy-ci.json.txt](https://github.com/wpilibsuite/sysid/files/6558888/noisy-ci.json.txt)

sysid crashes instead of catching the exception. `main` does this too.

**Comment by Piphi5** [comment]
I can't seem to reproduce this issue, it catches it for me.

**Comment by Piphi5** [comment]
It segfaults when we try to automatically calculate the qv and qp for the LQR since it doesn't have any valid data to go off of. Fix will be pushed soon.

File: sysid-application/src/main/native/cpp/view/Analyzer.cpp [hunk 4]
```diff
@@ -29,6 +29,8 @@
 
 using namespace sysid;
 
+static double badDataGain = -9999.0;
```
Comment (calcmogul) [inline sysid-application/src/main/native/cpp/view/Analyzer.cpp:32]:
```suggestion
static constexpr double kBadDataGain = -9999.0;
```

**Comment by calcmogul** [comment]
That fixed the crash, but I'm noticing that when LQR throws an exception, the GUI just doesn't show anything and doesn't open a pop-up with the exception body.

**Comment by Piphi5** [comment]
Is that when you apply the previous patch and load the noisy data?

**Comment by calcmogul** [comment]
Yea

File: sysid-application/src/main/native/cpp/view/Analyzer.cpp (hunk 4 above)
Comment (Piphi5) [reply sysid-application/src/main/native/cpp/view/Analyzer.cpp:32]: The compiler doesn't like the fact that I try to convert the const double* to a regular double* for the InputDouble method. Is there any way to work around that?

Comment (calcmogul) [reply sysid-application/src/main/native/cpp/view/Analyzer.cpp:32]: Oh, ok.

**Comment by Piphi5** [comment]
When files are initially read, any popup that is opened would only be opened once, therefore not staying around long enough for someone to see it. So now the popup is triggered by a boolean rather than opening it to work around this.

**Review by calcmogul — APPROVED** [review]
