### PR TITLE
Fix deployed JSON generation

### LINKED ISSUE #174: RoboRIO project fails to run
Running the latest main build #169 on Windows x86_64, I can successfully deploy, but running the robot code gives the following error:

```
﻿﻿﻿﻿﻿﻿﻿  ﻿
﻿﻿﻿﻿﻿﻿ ********** Robot program starting ********** ﻿
﻿﻿﻿﻿﻿﻿ reading json  ﻿
﻿﻿﻿﻿﻿﻿ Project failed: [json.exception.type_error.304] cannot use at() with array ﻿
﻿﻿﻿﻿﻿﻿  ﻿
﻿﻿﻿﻿﻿﻿ ********** Robot program starting ********** ﻿
﻿﻿﻿﻿﻿﻿ reading json  ﻿
﻿﻿﻿﻿﻿﻿ Project failed: [json.exception.type_error.304] cannot use at() with array ﻿
﻿﻿﻿﻿﻿﻿ NT: server: client CONNECTED: 169.254.92.114 port 54101 ﻿
﻿﻿﻿﻿﻿﻿ NT: server: client CONNECTED: 169.254.92.114 port 54102 ﻿

```

Here is the config file (on my machine):

```json
{
  "counts per rotation": 1.0,
  "encoder type": "Built-In",
  "encoding": false,
  "gearing": 18.0,
  "gyro": "NavX",
  "gyro ctor": "SerialPort.kUSB",
  "is drivetrain": false,
  "motor controllers": [
    "SPARK MAX (Brushless)"
  ],
  "number of samples per average": 1,
  "primary encoder inverted": false,
  "primary encoder ports": [
    0,
    1
  ],
  "primary motor ports": [
    5
  ],
  "primary motors inverted": [
    false
  ],
  "secondary encoder inverted": false,
  "secondary encoder ports": [
    2,
    3
  ],
  "secondary motor ports": [
    2
  ],
  "secondary motors inverted": [
    false
  ],
  "velocity measurement period": 100
}
```

Here is the json file on the roboRIO

```json
[{"counts per rotation":1.0,"encoder type":"Built-In","encoding":false,"gearing":18.0,"gyro":"NavX","gyro ctor":"SerialPort.kUSB","is drivetrain":false,"motor controllers":["SPARK MAX (Brushless)"],"number of samples per average":1,"primary encoder inverted":false,"primary encoder ports":[0,1],"primary motor ports":[5],"primary motors inverted":[false],"secondary encoder inverted":false,"secondary encoder ports":[2,3],"secondary motor ports":[2],"secondary motors inverted":[false],"velocity measurement period":100}]
```

### PR DESCRIPTION
**Pull request by Piphi5**
The initializer list constructor of the json library causes config jsons
to be converted into an array type causing issues when reading it on the
rio. Tests have been added to ensure this won't happen.

Fixes #174

### CODE REVIEW

File: sysid-application/src/main/native/include/sysid/deploy/DeploySession.h [hunk 1]
```diff
@@ -64,6 +64,11 @@ class DeploySession {
    */
   static std::vector<std::string> GetAddressesToTry(int team);
 
+  /**
+   * Returns the stored JSON object
+   */
+  wpi::json GetJSON() const { return m_config; }
```
Comment (prateekma) [inline sysid-application/src/main/native/include/sysid/deploy/DeploySession.h:70]: Can we just use const-reference here?

File: sysid-application/src/test/native/cpp/deploy/DeployJSONTest.cpp [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+#include "sysid/generation/ConfigManager.h"
+
+TEST(DeployTest, JSONGeneration) {
+  wpi::Logger m_logger;
+  sysid::ConfigSettings m_config;
+  sysid::ConfigManager m_configManager{m_config, m_logger};
+  sysid::DeploySession m_session{"0", false, m_configManager.Generate(1),
+                                 m_logger};
+
+  auto json = m_session.GetJSON();
```
Comment (prateekma) [inline sysid-application/src/test/native/cpp/deploy/DeployJSONTest.cpp:19]: Change to `const auto&` if above change is made.

**Review by prateekma — CHANGES_REQUESTED** [review]

File: sysid-application/src/main/native/include/sysid/deploy/DeploySession.h (hunk 1 above)
Comment (Piphi5) [reply sysid-application/src/main/native/include/sysid/deploy/DeploySession.h:70]: Yeah that's probably best

**Review by prateekma — APPROVED** [review]
